name: Update Main Version
run-name: Move ${{ github.event.inputs.release_tag }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
        default: "main"
      release_tag:
        type: string
        description: "Release version, ex: v3.x.x"
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Tag new target
      run: git tag -f ${{ github.event.inputs.release_tag }} ${{ github.event.inputs.target }}
    
    - name: Push new tag
      run: git push origin ${{ github.event.inputs.release_tag }} --force
    
    - name: Create new release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ github.event.inputs.release_tag }}
        prerelease: false
        title: ${{ github.event.inputs.release_tag }}
        files: |
          dist/*
          LICENSE